### ISSUE TITLE
License

### ISSUE THREAD

**Issue by phiresky** [Razacx/osuBMParser#1]
Hi,
I wanted to use this parser for a project of mine, but you haven't added a LICENSE file. It would be great if you could add one. I'd suggest MIT: https://opensource.org/licenses/MIT.

Thanks!

**Comment by N3bby** [comment]
I don't know anything about licensing.
If you want to use this code, go ahead, no restrictions

There are other libraries out there that are more complete than this one though I think

**Comment by phiresky** [comment]
Thanks.

> There are other libraries out there that are more complete than this one though I think

Not for C# as far as I saw
