### ISSUE TITLE
Error: Input String was no in correct format

### ISSUE THREAD

**Issue by fgrg2801** [Razacx/osuBMParser#3]
I get this error (Input String was no in correct format) when parsing some beatmaps, but other beatmaps parse normally without this error. I am using it on unity engine.

These beatmaps get this error:
- 316573 KYARY PAMYU PAMYU - Ninjya Re Bang Bang
- 403427 xi - Akasha

These beatmaps doesn't
 - 23760 Spiritsoulxx - Bad Apple!!
- 81259 Tsukasa - Music of the Spheres

**Comment by N3bby** [comment]
The issue with these beatmaps is that they were using decimal fractions for some beatmap variables that should be integers (as seen here https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format) ).
(The variable that was causing an issue in this case was TimelineZoom)

I created a fix that just drops everything behind the '.' when the type should be an int.

14f973411c1ade171c1f95085665b5a3e883fba6
